// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08/01/2026, 22.13.32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/composables/**/*.{js,ts,mjs}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/utils/**/*.{js,ts,mjs}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Asus/Documents/Rayival/portofolio/Portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;